
services:
  backend:
    platform: linux/amd64
    container_name: backend-phutunghd
    image: tranhieuphuc12/express-api-phutunghd:latest
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - .env
    restart: always

  mongodb:
    image: mongo
    volumes:
      - mongo-data:/data/phutungdb
    restart: always

volumes:
  mongo-data:
