services:
  backend-phutunghd:
    platform: linux/amd64
    container_name: backend-phutunghd
    image: tranhieuphuc12/express-api-phutunghd:latest
    expose:
      - 3001
    depends_on:
      - mongodb
    env_file:
      - .env
    restart: always
    networks:
      - nginx_network

  phutunghd-mongodb:
    image: mongo
    command: mongod --bind_ip_all
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=tranhieuphuc12
    volumes:
      - mongodb_data:/data/phutungdb
    restart: always
    networks:
      - nginx_network

volumes:
  mongodb_data:

networks:
  nginx_network:
    external: true